### ISSUE TITLE
Not a valid file

### ISSUE THREAD

**Issue by Stevepunk** [Ibrahim-Islam/monokai-vs-2015#3]
---
## OK   

I'm using VS 2015 Community

**Comment by mii9000** [comment]
@Mr-Steam How are you getting the file from this repo? I am suspecting that the file was not saved to your local drive in valid format in the first place. You can read about same problem [here](http://winterdom.com/2010/04/metroline-a-vs2010-color-scheme/comment-page-1#comment-1688).

**Comment by JordanCWalsh** [comment]
Downloading the zip file and using your instructions in README worked flawlessly for my VS2015 community version. My eyes are instantly more comfortable while coding in VS, thank you very much.
