### ISSUE TITLE
Cannot import Monokai setting to VS 2015 Pro

### ISSUE THREAD

**Issue by arxene** [Ibrahim-Islam/monokai-vs-2015#5]
I tried importing the settings, but in the wizard it said "The settings in file '<path redacted>\monokai_15.vssettings' cannot be imported because this file is not a valid .vssettings file.

(path redacted wasn't actually in the popup error box. I just didn't want to show my file system)

Using Microsoft Visual Studio Professional 2015. Version 14.0.25123.00 Update 2.
On Windows 7 Enterprise Service Pack 1 x64

![capture](https://cloud.githubusercontent.com/assets/10872377/22838313/35b99b04-ef8a-11e6-8376-d344b0d81979.PNG)

**Comment by mii9000** [comment]
I can check it out on a Pro version later but I use Community version and it seems to be working fine for me. Did you download the zip of the whole repo or just saved the vssettings file?

**Comment by arxene** [comment]
I just saved the vs settings file.

On Fri, Feb 10, 2017, 1:43 PM Ibrahim Islam <notifications@github.com>
wrote:

I can check it out on a Pro version later but I use Community version and
it seems to be working fine for me. Did you download the zip of the whole
repo or just saved the vssettings file?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ibrahim-Islam/monokai-vs-2015/issues/5#issuecomment-279046644>,
or mute the thread

**Comment by mii9000** [comment]
Someone else reported the same problem before also while saving the file directly. So, just download the zip and it should be fine.

**Comment by arxene** [comment]
Thank you, I will try that!
